name: voipmax
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  flutter_spinkit: ^5.2.0
  flutter_dialpad: ^1.0.5
  sip_ua: ^0.5.8
  shared_preferences: ^2.2.1
  permission_handler: ^11.3.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter_webrtc: ^0.9.48+hotfix.1
  flutter_local_notifications: ^16.3.2
  http: ^1.2.1
  unique_identifier: ^0.3.0
  share_plus: ^7.2.2
  flutter_callkit_incoming: ^2.0.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
