// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNu9nPzWv-JAFdp8ppyWvpVfiYCmfeT-E',
    appId: '1:607760043187:web:505bb869236e1f3cae34c6',
    messagingSenderId: '607760043187',
    projectId: 'mytell-c2438',
    authDomain: 'mytell-c2438.firebaseapp.com',
    storageBucket: 'mytell-c2438.appspot.com',
    measurementId: 'G-BCZY9S2Y8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmZnPOmorvBxV3p-hwPNvFtYsFhV1VfZQ',
    appId: '1:607760043187:android:906d70e2768207f2ae34c6',
    messagingSenderId: '607760043187',
    projectId: 'mytell-c2438',
    storageBucket: 'mytell-c2438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjK4b2HyAqTuEsQde8zYi4zn7VSiy-yS8',
    appId: '1:607760043187:ios:8161ab6cd60aea35ae34c6',
    messagingSenderId: '607760043187',
    projectId: 'mytell-c2438',
    storageBucket: 'mytell-c2438.appspot.com',
    iosBundleId: 'com.example.voipmax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjK4b2HyAqTuEsQde8zYi4zn7VSiy-yS8',
    appId: '1:607760043187:ios:0c3463fcd2e502f0ae34c6',
    messagingSenderId: '607760043187',
    projectId: 'mytell-c2438',
    storageBucket: 'mytell-c2438.appspot.com',
    iosBundleId: 'com.example.voipmax.RunnerTests',
  );
}
